typography_spectrum: 0.7271336007397622
color:
  brandStrength: 0.21579398005269468
  lightness: 0.890060086036101
  saturation: 0.5737058417871594
  rhythmicContrast: 0.05498255230486393
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
layout_spectrum: 0.41667669429443777
author:
  email: eric@cuveeimports.com
  name: Eric Frick
name: CuvÃ©e Imports
navigation:
  - id: 87f380ac-587c-4c24-91c6-2d9fec307947
    name: Producers
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8089acec-4134-4051-a7e8-689445a884fb.jpg
